
###postGis配置
postgreSqlDatabase: postgis_24_sample
postgreSqlHost: 192.168.2.229
postgreSqlPort: 5432
postgreName: root
postgreSqlPassword: xiaoyi
postgreSqlDriver: org.postgresql.Driver

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG9Dialect
        format_sql: true
        hbm2ddl:
          auto: update
        jdbc.lob.non_contextual_creation: true
        temp:
          # 兼容SpringBoot2.X, 关闭 Hibernate尝试验证PostgreSQL的CLOB特性
          use_jdbc_metadata_defaults: false
    show-sql: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG9Dialect
  datasource:
    platform: postgres
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:postgresql://${postgreSqlHost}:${postgreSqlPort}/${postgreSqlDatabase}?useSSL=false
      username: ${postgreName}
      password: ${postgreSqlPassword}
      driverClassName: ${postgreSqlDriver}
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 10000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT VERSION()
      #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，
      #如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filter:
        # 配置StatFilter
        stat:
          db-type: postgresql
          log-slow-sql: true
          slow-sql-millis: 2000
        # 配置WallFilter
        wall:
          enabled: true
          db-type: postgresql
          config:
            delete-allow: true
            drop-table-allow: false

