
###Redis配置
redisDatabase: 2
redisHost: 47.92.213.93
redisPort: 6379
redisPassword: xiaoyi

###Redis配置
spring:
  redis:
    ###Redis数据库索引（默认为0）
    database: ${redisDatabase}
    host: ${redisHost}
    port: ${redisPort}
    password: ${redisPassword}
    lettuce:
      pool:
        ###连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        ###连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        ###连接池中的最大空闲连接
        max-idle: 5
        ###连接池中的最小空闲连接
        min-idle: 0
    ###连接超时时间（毫秒）
    timeout: 10000ms
